// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIC2bVqwzEuI_jlpJE-mr91lE3giJYh7k',
    appId: '1:940336213780:web:19849f0f386313c6bf9c01',
    messagingSenderId: '940336213780',
    projectId: 'restaurant-app-d9232',
    authDomain: 'restaurant-app-d9232.firebaseapp.com',
    storageBucket: 'restaurant-app-d9232.firebasestorage.app',
    measurementId: 'G-5H7RNSY40M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dmhW0ooSl2ALaL74QuR6At1SHawuE4c',
    appId: '1:940336213780:android:2ec732bc5da759f7bf9c01',
    messagingSenderId: '940336213780',
    projectId: 'restaurant-app-d9232',
    storageBucket: 'restaurant-app-d9232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSRvKxZWFXcloqo8Mcjxv-30NRIW-kNyg',
    appId: '1:940336213780:ios:8e3f39675cc931dbbf9c01',
    messagingSenderId: '940336213780',
    projectId: 'restaurant-app-d9232',
    storageBucket: 'restaurant-app-d9232.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSRvKxZWFXcloqo8Mcjxv-30NRIW-kNyg',
    appId: '1:940336213780:ios:8e3f39675cc931dbbf9c01',
    messagingSenderId: '940336213780',
    projectId: 'restaurant-app-d9232',
    storageBucket: 'restaurant-app-d9232.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIC2bVqwzEuI_jlpJE-mr91lE3giJYh7k',
    appId: '1:940336213780:web:5f8c668077824383bf9c01',
    messagingSenderId: '940336213780',
    projectId: 'restaurant-app-d9232',
    authDomain: 'restaurant-app-d9232.firebaseapp.com',
    storageBucket: 'restaurant-app-d9232.firebasestorage.app',
    measurementId: 'G-2996016R6J',
  );
}
